Output demo.gif

Set Shell "bash"
Set FontSize 16
Set Width 1000
Set Height 600
Set Theme "Dracula"

Type "java -cp bin com.callcenter.Main"
Enter
Sleep 1s

Type "2"
Enter
Sleep 1s

Type "1"
Enter
Sleep 500ms
Type "Carlota Joaquina"
Enter
Sleep 500ms
Type "3"
Enter
Sleep 1s

Type "1"
Enter
Sleep 500ms
Type "Vlad III"
Enter
Sleep 500ms
Type "1"
Enter
Sleep 1s

Type "2"
Enter
Sleep 1s

Type "3"
Enter
Sleep 1s

Type "5"
Enter
Sleep 2s
